dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost 
      user: admin
      password: admin123
      port: 5432
      dbname: olist_db
      schema: dwh
      threads: 4
    ci:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASS', 'postgres') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      dbname: "{{ env_var('DB_NAME', 'postgres') }}"
      schema: dwh
      threads: 4